In [2]:
import pandas as pd

In [25]:
players = pd.read_csv("rpl_players.csv")
players.head()

,shirt_number,player_id,player_name,position,date_of_birth,age,nationality,height_m,foot,joined,contract_end,market_value_eur,player_profile_url,club_id,club_slug
0,70,867082,Abakar Gadzhiev,Attacking Midfield,31/12/2003,22,Russia,1.80,left,01/07/2025,30/06/2029,500000.0,https://www.transfermarkt.com/abakar-gadzhiev/...,3725,akhmat-grozny
1,27,1033039,Akhmed Davlitgereev,Right Midfield,14/02/2005,21,Russia,1.76,left,19/02/2026,30/06/2026,NaN,https://www.transfermarkt.com/akhmed-davlitger...,3725,akhmat-grozny
2,9,373374,Brian Mansilla,Left Winger,16/04/1997,29,Argentina,1.78,left,01/07/2025,30/06/2028,1500000.0,https://www.transfermarkt.com/brian-mansilla/p...,3725,akhmat-grozny
3,82,621436,Daniil Khlusevich,Right-Back,26/02/2001,25,"Russia, Ukraine",1.86,right,18/02/2026,30/06/2026,2500000.0,https://www.transfermarkt.com/daniil-khlusevic...,3725,akhmat-grozny
4,2,917402,Dzhamalutdin Abdulkadyrov,Centre-Back,23/03/2005,21,Russia,1.95,left,19/02/2026,30/06/2026,1000000.0,https://www.transfermarkt.com/dzhamalutdin-abd...,3725,akhmat-grozny

In [12]:
players.shape

(446, 14)

In [9]:
players = players.drop_duplicates(subset=["player_id", "club_id"])
players.to_csv("rpl_players_clean.csv", index=False)

In [7]:
players[["club_slug", "club_id"]].drop_duplicates().to_csv("rpl_clubs.csv", index=False)

In [8]:
players[players.player_id.isna()]

,player_id,player_name,position,date_of_birth,age,nationality,height_m,foot,joined,signed_from,contract_end,market_value_eur,club_id,club_slug
220,NaN,Roman Safronov,Goalkeeper,15/02/2003,23,NaN,1.92,NaN,01/01/2025,NaN,30/06/2028,100000.0,16704,fk-krasnodar
331,NaN,Stanislav Lapinskiy,Centre-Forward,15/02/2005,21,NaN,1.83,right,04/07/2024,NaN,30/06/2027,75000.0,49702,fk-nizhny-novgorod
409,NaN,Stepan Melnikov,Right Winger,25/04/2002,24,NaN,1.78,left,20/01/2022,NaN,30/06/2026,50000.0,1083,fk-rostov

In [26]:
stats = pd.read_csv("rpl_club_stats.csv")
stats.head()

,club_slug,club_id,season,player_id,appearances,goals,assists,yellow_cards,second_yellow_cards,red_cards,substitutions_on,substitutions_off,ppg,minutes_played
0,akhmat-grozny,3725,2025,51274,0,0,0,0,0,0,0,0,0.00,0
1,akhmat-grozny,3725,2025,58971,14,0,1,1,0,0,0,0,1.14,1260
2,akhmat-grozny,3725,2025,253734,22,1,0,4,1,1,0,5,1.23,1857
3,akhmat-grozny,3725,2025,267383,12,0,0,0,0,0,10,1,1.17,302
4,akhmat-grozny,3725,2025,273945,26,0,1,1,0,0,0,2,1.23,2299

In [11]:
stats.to_csv("rpl_club_stats.csv", index=False)